<!-- 网站主体 -->
<div class="bodymain">
	<!-- 登录 -->
	<div class="logins">
    	<div class="namepsd">
        	<span>用户名</span>
            <p><input type="text" name="adminlogin" id="adminlogin" class="inputlogin"></p>
        </div>
        <div class="namepsd">
        	<span>密码</span>
            <p><input type="password" name="adminpwd" id='adminpwd' class="inputlogin"></p>
        </div>
        <div class="namepsd">
        	<input type="button" value="登 录" class="loginbtn" onclick="adminlogin()" />
        </div>
    </div>
</div>