<div class="footer">
    <div class="wevvice_con">
        <div class="service line_ser">
            <ul class="us">
                <h3 class="ser_tit line_ser">联系我们</h3>
                <li class="while">工作时间9:00--18:00</li>
                <li class="qq">2475252675</li>
                <li class="phone">4008-900-512</li>
                <li class="email">service@huafaner.com</li>
            </ul>
            <ul class="promise">
                <h3 class="ser_tit line_ser">我们承诺</h3>
                <li>
                    <p class="pm_a1"></p>
                    <div>资深花艺师经典设计</div>
                </li>
                <li>
                    <p class="pm_a2"></p>
                    <div>100%新鲜优质花材</div>
                </li>
                <li>
                    <p class="pm_a3"></p>
                    <div>全新设计每月上市</div>
                </li>
            </ul>
            <ul class="attention">
                <h3 class="ser_tit line_ser">关注我们</h3>
                <li><a href="http://www.weibo.com/floralstyle" target="_blank" class="ser_sina">关注新浪微博</a></li>
                <li><a href="" class="ser_weixin">关注微信</a></li>
                <li><a href="http://blog.huafaner.com" target="_blank" class="ser_ddian">关注点点博客</a></li>
            </ul>
        </div>
        
        <div class="service">
            <dl>
                <dt><img src="images/bot_logo.gif" /></dt>
                <dd class="bot_line"><a href="#">iPhone客户端下载</a></dd>
                <dd class="bot_line"><a href="about.php">关于花范儿</a></dd>
                <dd class="bot_line"><a href="service.php">服务条款</a></dd>
                <dd class=""><a href="#">友情链接</a></dd>
            </dl>
        </div>
        <div class="service_copy">
            huafaner.com &copy;  2011-2012 All Rights Resered<br />
            www.huafaner.com 京ICP备12035699号
        </div>
    </div>
</div>