<dl>
    <dt>商品管理</dt>
    <dd><a href="admin.php?k=prod">发布商品</a></dd>
    <dd><a href="admin.php?k=prodlist">维护商品</a></dd>
    <dd><a href="admin.php?k=dict&dict_type=prod_type">维护商品分类</a></dd>
    <dd><a href="admin.php?k=dict&dict_type=prod_care_desc">维护保养说明</a></dd>
    <dd><a href="admin.php?k=dict&dict_type=prod_order_desc">维护订购说明</a></dd>
    <dd><a href="admin.php?k=dict&dict_type=prod_tag">维护商品标签</a></dd>
</dl>
<dl>
    <dt>专题管理</dt>
    <dd><a href="admin.php?k=sub">发布专题</a></dd>
    <dd><a href="admin.php?k=pub">发布活动</a></dd>
    <dd><a href="admin.php?k=sublist">维护专题</a></dd>
    <dd><a href="admin.php?k=publist">维护活动</a></dd>
</dl>
<dl>
    <dt>会员管理</dt>
    <dd><a href="会员查询.html">会员查询</a></dd>
</dl>
<dl>
    <dt>详单管理</dt>
    <dd><a href="admin.php?k=orderlist">详单查询</a></dd>
</dl>
<dl>
    <dt>优惠券管理</dt>
    <dd><a href="优惠券发放.html">优惠券发放</a></dd>
    <dd><a href="优惠券查询.html">优惠券查询</a></dd>
</dl>
<dl>
    <dt>页面管理</dt>
    <dd><a href="admin.php?k=design_index">首页</a></dd>
    <dd><a href="admin.php?k=design_sub">专题活动页</a></dd>
    <dd><a href="admin.php?k=bloglist">博客列表</a></dd>
    <dd><a href="admin.php?k=blog">发表博客</a></dd>
</dl>