<!--<div class="adminmenu">
    专题维护
    <ul>
        <li><a href="admin.php?k=adminsublist">专题列表</a></li>
        <li><a href="admin.php?k=adminsub">发布专题</a></li>
    </ul>
    <hr/>
    商品维护
    <ul>
        <li><a href="admin.php?k=adminprodlist">商品列表</a></li>
        <li><a href="admin.php?k=adminprod">发布商品</a></li>
        <li><a href="admin.php?k=admindict">字典信息</a></li>
    </ul>
    <hr/>
    独一无二
    <ul>
        <li><a href="admin.php?k=adminonlyprodlist">商品列表</a></li>
        <li><a href="admin.php?k=adminonlyprod">发布商品</a></li>
    </ul>
    订单管理
    <ul>
        <li><a href="admin.php?k=adminorderlist">订单管理</a></li>
    </ul>
    <a href="javascript:void(0)" onclick="adminlogout()">退出登陆</a>
    <hr/>
</div>
-->
<dl>
    <dt>商品管理</dt>
    <dd><a href="admin.php?k=prod">发布商品</a></dd>
    <dd><a href="admin.php?k=prodlist">维护商品</a></dd>
    <dd><a href="admin.php?k=dict&dict_type=prod_type">维护商品分类</a></dd>
    <dd><a href="admin.php?k=dict&dict_type=prod_care_desc">维护保养说明</a></dd>
    <dd><a href="admin.php?k=dict&dict_type=prod_order_desc">维护订购说明</a></dd>
    <dd><a href="admin.php?k=dict&dict_type=prod_tag">维护商品标签</a></dd>
</dl>
<dl>
    <dt>专题管理</dt>
    <dd><a href="发布专题.html">发布专题</a></dd>
    <dd><a href="发布活动.html">发布活动</a></dd>
    <dd><a href="维护专题.html">维护专题</a></dd>
    <dd><a href="维护活动.html">维护活动</a></dd>
</dl>
<dl>
    <dt>会员管理</dt>
    <dd><a href="会员查询.html">会员查询</a></dd>
</dl>
<dl>
    <dt>详单管理</dt>
    <dd><a href="详单查询.html">详单查询</a></dd>
    <dd><a href="修改订单.html">修改订单</a></dd>
</dl>
<dl>
    <dt>优惠券管理</dt>
    <dd><a href="优惠券发放.html">优惠券发放</a></dd>
    <dd><a href="优惠券查询.html">优惠券查询</a></dd>
</dl>
<dl>
    <dt>页面管理</dt>
    <dd class="sel"><a href="首页.html">首页</a></dd>
    <dd><a href="专题活动页.html">专题活动页</a></dd>
</dl>